language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules
install:
  - npm i

script:
  - npm run test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: spendings.surge.sh
  on:
    branch: master