language: node_js
node_js:
  - "12.10"

cache:
  directories:
    - node_modules
install:
  - yarn install

script:
  - npm run test
  - rm -f src/package.alias.json
  - cd src; ln -s ../package.json package.alias.json; cd ..
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: spendings.surge.sh
  on:
    branch: master